openapi: 3.0.0
info:
  version: 1.0.0
  title: Poker Hand List
  description: 'API para comprobar manos de poker y calcular el ganador  '
  contact:
    name: David
    email: davbrican@alum.ues.es
    url: 'https://github.com/dbrincauus'
  license:
    name: MIT
    url: 'http://opensource.org/licenses/MIT'
paths:
  /api/v1/checkingHand:
    post:
      description: Check the poker hands
      operationId: handCheck
      responses:
        '201':
          description: example created
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorModel'
      requestBody:
        x-name: example
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/example'
        description: Example to be created
        required: true
    options:
      description: Check the poker hands
      operationId: handCheckOptions
      responses:
        '201':
          description: example created
        default:
          description: unexpected error
          content:
            text/plain:
              schema:
                type: string
      requestBody:
        x-name: example
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/example'
        description: Example to be created
        required: true
components:
  schemas:
    errorModel:
      type: array
      required:
        - lista
      properties:
        lista:
          type: array
    example:
      type: array
      uniqueItems: true
      minItems: 1
      items:
        required:
          - bote
        properties:
          jugadas:
            type: array
            uniqueItems: true
            minItems: 1
            items:
              required:
                - jugador
                - apuesta
              properties:
                jugador:
                  type: string
                  minLength: 1
                apuesta:
                  type: number
                cartas:
                  type: array
                  uniqueItems: true
                  minItems: 1
                  items:
                    required:
                      - valor
                      - palo
                    properties:
                      valor:
                        type: string
                        minLength: 1
                      palo:
                        type: string
                        minLength: 1
          bote:
            type: string
            minLength: 1
      required:
        - lista
